import { Event } from "../models/event.model";

export const events: Event[] = [
    {
        id: 'evt-001',
        cameraId: 'cam-001',
        cameraName: 'Main Entrance',
        type: 'person',
        thumbnailPath: '/mock/events/event-thumbnail.png',
        videoPath: '/assets/mock/videos/event-001.mp4',
        isRead: false,
        timestamp: new Date('2026-07-23T18:45:00'),
    },
    {
        id: 'evt-002',
        cameraId: 'cam-002',
        cameraName: 'Parking Lot',
        type: 'person',
        thumbnailPath: '/mock/events/event-thumbnail.png',
        videoPath: '/assets/mock/videos/event-002.mp4',
        isRead: true,
        timestamp: new Date('2026-07-23T18:30:00'),
    },
    {
        id: 'evt-003',
        cameraId: 'cam-003',
        cameraName: 'Warehouse',
        type: 'person',
        thumbnailPath: '/mock/events/event-thumbnail.png',
        videoPath: '/assets/mock/videos/event-003.mp4',
        isRead: false,
        timestamp: new Date('2026-07-23T18:10:00'),
    },
    {
        id: 'evt-004',
        cameraId: 'cam-001',
        cameraName: 'Main Entrance',
        type: 'person',
        thumbnailPath: '/mock/events/event-thumbnail.png',
        videoPath: '/assets/mock/videos/event-004.mp4',
        isRead: true,
        timestamp: new Date('2026-07-23T17:55:00'),
    },
    {
        id: 'evt-005',
        cameraId: 'cam-004',
        cameraName: 'Reception',
        type: 'person',
        thumbnailPath: '/mock/events/event-thumbnail.png',
        videoPath: '/assets/mock/videos/event-005.mp4',
        isRead: false,
        timestamp: new Date('2026-07-23T17:40:00'),
    },
];